### ISSUE TITLE
adding email confirmation to an api note

### ISSUE THREAD

**Issue by seastan** [mreishus/notebook-pub#1]
Thanks for your note on adding email confirmation to a website.

I have managed to get a mailer working with my site, and using your code I'm able to receive an email when I sign up that contains the confirmation url. Upon clicking it, I am greeted by a message saying that my email has been confirmed. However, I do not see the users "email_confirmed_at" updating in the database. Taking a look at the `confirmation_controller.ex` file:
```
defmodule MyAppWeb.API.V1.ConfirmationController do
  use MyAppWeb, :controller

  alias Plug.Conn

  @spec show(Conn.t(), map()) :: Conn.t()
  def show(conn, %{"id" => token}) do
    case PowEmailConfirmation.Plug.load_user_by_token(conn, token) do
      {:error, conn} ->
        conn
        |> put_status(401)
        |> json(%{error: %{status: 401, message: "Invalid confirmation code"}})

      {:ok, conn} ->
        conn
        |> json(%{success: %{message: "Email confirmed"}})
    end
  end
end
```
Where is the magic happening here? I would have assumed we'd need some kind of code that updates the database in {:ok, conn} like...
```
      {:ok, conn} ->
        conn
        |> Pow.Plug.update_user(%{"email_confirmed_at" => DateTime.utc_now})
        |> case do
          {:ok, user, conn} ->
            conn
            |> json(%{success: %{message: "Email confirmed"}})
          {:error, changeset, conn} ->
            errors = Changeset.traverse_errors(changeset, &ErrorHelpers.translate_error/1)
            conn
            |> put_status(500)
            |> json(%{error: %{status: 500, message: "Couldn't confirm email", errors: errors}})
        end
```
This doesn't work though
```
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function nil.__struct__/0 is undefined
        nil.__struct__()
        (pow 1.0.19) lib/pow/ecto/context.ex:154: Pow.Ecto.Context.update/3
        (pow 1.0.19) lib/pow/plug.ex:146: Pow.Plug.update_user/2
```

**Comment by MistaIA** [comment]
on `{:ok, conn}`, I think you can just use: `PowEmailConfirmation.Plug.confirm_email(conn, params)`.
